name: SmartDownloader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Download Windows wheels
      run: |
        mkdir -p dist
        pip download torch torchvision torchaudio \
          --platform win_amd64 \
          --python-version 311 \
          --implementation cp \
          --abi cp311 \
          --only-binary=:all: \
          --no-deps \
          -d dist

    - name: Zip package
      run: |
        cd dist
        zip -r package.zip *.whl

    - name: Commit files
      run: |
        git config user.name github-actions
        git config user.email actions@github.com
        git add dist/*
        git commit -m "update wheels" || echo "no changes"
        git pull --rebase --autostash origin ${{ github.ref_name }}
        git push
